### PR TITLE
Fix for OM-55783: fix handling anti affinity rule meant to distribute…

### PR DESCRIPTION
**Pull request by irfanurrehman**
… replicas on different nodes.
Fixes https://vmturbo.atlassian.net/browse/OM-55783

cc @enlinxu @pallavidn

### CODE REVIEW

**Comment by irfanurrehman** [comment]
@enlinxu @evat-pm Please let me know if this might be needed for 6.x

**Comment by evat-pm** [comment]
Regarding 6.4.x: Given that customers and prospects will still be using 6.4.x Turbo Server for Azure use cases, if the effort is low, we should and create a 6.4.5 kubeturbo.

**Comment by evat-pm** [comment]
Spoke to @enlinxu and we will port to 6.4.x if we see in customer's environment and they cannot update to 7.21

**Comment by ading1977** [comment]
There are a bunch of test failures:

**Comment by ading1977** [comment]
There are a bunch unit test failures:

```
pkg/discovery/worker/compliance/affinity_commodity_manager_test.go:244:84: not enough arguments in call to acm.GetAccessCommoditiesForPodAffinityAntiAffinity
	have ([]"k8s.io/api/core/v1".PodAffinityTerm)
	want ([]"k8s.io/api/core/v1".PodAffinityTerm, *"k8s.io/api/core/v1".Pod)
```

```
=== RUN   TestAnyPodMatchesPodAffinityTerm
--- FAIL: TestAnyPodMatchesPodAffinityTerm (0.00s)
    affinity_helper_test.go:480: Test case 0 failed. Expects true, got false.
=== RUN   TestSatisfiesPodsAffinityAntiAffinity
--- FAIL: TestSatisfiesPodsAffinityAntiAffinity (0.00s)
    affinity_helper_test.go:658: Test case 0 failed. Expects true, got false.
    affinity_helper_test.go:658: Test case 1 failed. Expects false, got true.
=== RUN   TestInterPodAffinityMatches
--- FAIL: TestInterPodAffinityMatches (0.00s)
    affinity_helper_test.go:870: Test case 0 failed. Expects true, got false.
    affinity_helper_test.go:870: Test case 1 failed. Expects false, got true.
```

**Comment by irfanurrehman** [comment]
@enlinxu @ading1977 apologies for not looking at this earlier. Just had a look, I did miss to update the associated tests, wrt to the fix.  Updated the same. PTAL.

**Pull request merged**
