### PR TITLE
Aks autoscaling machine scaler implementation

### PR DESCRIPTION
**Pull request by irfanurrehman**
This implements two stories:
https://vmturbo.atlassian.net/browse/OM-65281
https://vmturbo.atlassian.net/browse/OM-65282

~~I have labelled it as wip because the test code implementation is still in progress and this code is untested. The could be reviewed neverthe less.
Please note that this is on top of #512 and only the last commit is reviewable here.~~
This is now tested on the resource group `adveng` azure cluster `aks-virtual`.

### CODE REVIEW

**Comment by irfanurrehman** [comment]
To run the integration test against the aks cluster (eg `aks-virtual`) use below:
```
# make integration
# ARM_SUBSCRIPTION_ID=“xxxxxxxx" ARM_TENANT_ID=“xxxxxxx” ARM_CLIENT_ID=“xxxxxxxx” ARM_CLIENT_SECRET=“xxxxxx” ARM_RESOURCE_GROUP="adveng" ARM_VM_TYPE="aks" AZURE_CLUSTER_NAME="aks-virtual" AZURE_NODE_RESOURCE_GROUP="MC_adveng_aks-virtual_westus" ./build/integration.test -k8s-kubeconfig <kubeconfig-absolute-path> -cp-node-groups "3:10:agentpool" -ginkgo.focus "Machine Scaling " -test.v -v=7
```

Please node that these are expensive operations and azure APIs can take as long as 10 mins for each complete provision/suspend operation.

**Comment by irfanurrehman** [comment]
The tests fail because of coveralls server issues. It seems the coveralls server is not able to cope up with the current traffic.

I ran the integration test against `azure` `adveng` `aks-virtual` cluster and both provision and suspen node tests pass:

```
Starting: /Users/irfanurrehman/bin/dlv-dap dap --listen=127.0.0.1:53078 --log-dest=3 from /Users/irfanurrehman/src/github.com/turbonomic/kubeturbo/test/integration
DAP server listening at: 127.0.0.1:53078
I0922 22:50:26.402673   98966 test_context.go:99] FLAG: --add_dir_header="false"
I0922 22:50:26.403214   98966 test_context.go:99] FLAG: --alsologtostderr="true"
I0922 22:50:26.403228   98966 test_context.go:99] FLAG: --cp-node-groups="[3:10:agentpool]"
I0922 22:50:26.403237   98966 test_context.go:99] FLAG: --ginkgo.debug="false"
I0922 22:50:26.403243   98966 test_context.go:99] FLAG: --ginkgo.dryRun="false"
I0922 22:50:26.403248   98966 test_context.go:99] FLAG: --ginkgo.failFast="false"
I0922 22:50:26.403252   98966 test_context.go:99] FLAG: --ginkgo.failOnPending="false"
I0922 22:50:26.403257   98966 test_context.go:99] FLAG: --ginkgo.flakeAttempts="1"
I0922 22:50:26.403263   98966 test_context.go:99] FLAG: --ginkgo.focus="Machine Scaling "
I0922 22:50:26.403271   98966 test_context.go:99] FLAG: --ginkgo.noColor="false"
I0922 22:50:26.403276   98966 test_context.go:99] FLAG: --ginkgo.noisyPendings="true"
I0922 22:50:26.403280   98966 test_context.go:99] FLAG: --ginkgo.noisySkippings="true"
I0922 22:50:26.403285   98966 test_context.go:99] FLAG: --ginkgo.parallel.node="1"
I0922 22:50:26.403290   98966 test_context.go:99] FLAG: --ginkgo.parallel.streamhost=""
I0922 22:50:26.403294   98966 test_context.go:99] FLAG: --ginkgo.parallel.synchost=""
I0922 22:50:26.403298   98966 test_context.go:99] FLAG: --ginkgo.parallel.total="1"
I0922 22:50:26.403303   98966 test_context.go:99] FLAG: --ginkgo.progress="false"
I0922 22:50:26.403308   98966 test_context.go:99] FLAG: --ginkgo.randomizeAllSpecs="false"
I0922 22:50:26.403313   98966 test_context.go:99] FLAG: --ginkgo.regexScansFilePath="false"
I0922 22:50:26.403318   98966 test_context.go:99] FLAG: --ginkgo.reportFile=""
I0922 22:50:26.403322   98966 test_context.go:99] FLAG: --ginkgo.reportPassed="false"
I0922 22:50:26.403328   98966 test_context.go:99] FLAG: --ginkgo.seed="1632315026"
I0922 22:50:26.403339   98966 test_context.go:99] FLAG: --ginkgo.skip=""
I0922 22:50:26.403344   98966 test_context.go:99] FLAG: --ginkgo.skipMeasurements="false"
I0922 22:50:26.403349   98966 test_context.go:99] FLAG: --ginkgo.slowSpecThreshold="5"
I0922 22:50:26.403357   98966 test_context.go:99] FLAG: --ginkgo.succinct="false"
I0922 22:50:26.403362   98966 test_context.go:99] FLAG: --ginkgo.trace="false"
I0922 22:50:26.403366   98966 test_context.go:99] FLAG: --ginkgo.v="false"
I0922 22:50:26.403371   98966 test_context.go:99] FLAG: --k8s-context=""
I0922 22:50:26.403375   98966 test_context.go:99] FLAG: --k8s-kubeconfig="/Users/irfanurrehman/configs/aks-virtual.conf"
I0922 22:50:26.403381   98966 test_context.go:99] FLAG: --kubeconfig=""
I0922 22:50:26.403385   98966 test_context.go:99] FLAG: --log-flush-frequency="5s"
I0922 22:50:26.403392   98966 test_context.go:99] FLAG: --log_backtrace_at=":0"
I0922 22:50:26.403406   98966 test_context.go:99] FLAG: --log_dir=""
I0922 22:50:26.403411   98966 test_context.go:99] FLAG: --log_file=""
I0922 22:50:26.403415   98966 test_context.go:99] FLAG: --log_file_max_size="1800"
I0922 22:50:26.403422   98966 test_context.go:99] FLAG: --logtostderr="false"
I0922 22:50:26.403427   98966 test_context.go:99] FLAG: --master=""
I0922 22:50:26.403431   98966 test_context.go:99] FLAG: --min-replica-count="0"
I0922 22:50:26.403435   98966 test_context.go:99] FLAG: --single-call-timeout="30s"
I0922 22:50:26.403441   98966 test_context.go:99] FLAG: --skip-nodes-with-local-storage="true"
I0922 22:50:26.403446   98966 test_context.go:99] FLAG: --skip-nodes-with-system-pods="true"
I0922 22:50:26.403450   98966 test_context.go:99] FLAG: --skip_headers="false"
I0922 22:50:26.403455   98966 test_context.go:99] FLAG: --skip_log_headers="false"
I0922 22:50:26.403459   98966 test_context.go:99] FLAG: --stderrthreshold="2"
I0922 22:50:26.403466   98966 test_context.go:99] FLAG: --test-namespace="kubeturbo-test"
I0922 22:50:26.403471   98966 test_context.go:99] FLAG: --test.bench=""
I0922 22:50:26.403475   98966 test_context.go:99] FLAG: --test.benchmem="false"
I0922 22:50:26.403480   98966 test_context.go:99] FLAG: --test.benchtime="1s"
I0922 22:50:26.403486   98966 test_context.go:99] FLAG: --test.blockprofile=""
I0922 22:50:26.403496   98966 test_context.go:99] FLAG: --test.blockprofilerate="1"
I0922 22:50:26.403502   98966 test_context.go:99] FLAG: --test.count="1"
I0922 22:50:26.403510   98966 test_context.go:99] FLAG: --test.coverprofile=""
I0922 22:50:26.403515   98966 test_context.go:99] FLAG: --test.cpu=""
I0922 22:50:26.403520   98966 test_context.go:99] FLAG: --test.cpuprofile=""
I0922 22:50:26.403525   98966 test_context.go:99] FLAG: --test.failfast="false"
I0922 22:50:26.403529   98966 test_context.go:99] FLAG: --test.list=""
I0922 22:50:26.403533   98966 test_context.go:99] FLAG: --test.memprofile=""
I0922 22:50:26.403537   98966 test_context.go:99] FLAG: --test.memprofilerate="0"
I0922 22:50:26.403542   98966 test_context.go:99] FLAG: --test.mutexprofile=""
I0922 22:50:26.403546   98966 test_context.go:99] FLAG: --test.mutexprofilefraction="1"
I0922 22:50:26.403551   98966 test_context.go:99] FLAG: --test.outputdir=""
I0922 22:50:26.403556   98966 test_context.go:99] FLAG: --test.paniconexit0="false"
I0922 22:50:26.403560   98966 test_context.go:99] FLAG: --test.parallel="12"
I0922 22:50:26.403565   98966 test_context.go:99] FLAG: --test.run=""
I0922 22:50:26.403569   98966 test_context.go:99] FLAG: --test.short="false"
I0922 22:50:26.403574   98966 test_context.go:99] FLAG: --test.testlogfile=""
I0922 22:50:26.403578   98966 test_context.go:99] FLAG: --test.timeout="0s"
I0922 22:50:26.403582   98966 test_context.go:99] FLAG: --test.trace=""
I0922 22:50:26.403587   98966 test_context.go:99] FLAG: --test.v="true"
I0922 22:50:26.403591   98966 test_context.go:99] FLAG: --v="7"
I0922 22:50:26.403598   98966 test_context.go:99] FLAG: --vmodule=""
=== RUN   TestIntegration
I0922 22:50:26.403683   98966 integration_test.go:52] Starting integration run on Ginkgo node 1
Running Suite: Kubeturbo integration suite
==========================================
Random Seed: 1632315026
Will run 2 of 6 specs
SSSS
I0922 22:50:26.409200   98966 action_handler.go:65] SCC's allowed: map[]
I0922 22:50:26.409287   98966 action_handler.go:141] the Cluster API is unavailable
I0922 22:50:31.116721   98966 machine_scale_executor.go:113] Building azure cloud provider.
I0922 22:50:31.116761   98966 machine_scale_executor.go:154] Creating Azure Manager with default configuration.
I0922 22:50:31.116817   98966 azure_manager.go:461] Starting azure manager with subscription ID "6a5d73a4-e446-4c75-8f18-073b2f60d851"
I0922 22:50:43.345415   98966 action_handler.go:359] Received an action PROVISION for entity VIRTUAL_MACHINE [aks-agentpool-36973178-0]
I0922 22:50:43.345466   98966 action_handler.go:176] Now wait for action result
I0922 22:50:44.901842   98966 machine_scaler_cp.go:71] Executing action Provision on node aks-agentpool-36973178-0 with node parent pool size 2.
I0922 22:50:45.208867   98966 azure_kubernetes_service_pool.go:131] Current size: 2, Target size requested: 3
I0922 23:01:52.264764   98966 action_handler.go:336] action keepAlive goroutine exit.

------------------------------
• [SLOW TEST:697.664 seconds]
Machine Scaling via Cloud Provider
/Users/irfanurrehman/src/github.com/turbonomic/kubeturbo/test/integration/machine_scaling_cp.go:16
  executing action provision machine
  /Users/irfanurrehman/src/github.com/turbonomic/kubeturbo/test/integration/machine_scaling_cp.go:53
    should result in new node being added
    /Users/irfanurrehman/src/github.com/turbonomic/kubeturbo/test/integration/machine_scaling_cp.go:54
------------------------------
I0922 23:02:04.079635   98966 action_handler.go:65] SCC's allowed: map[]
I0922 23:02:04.079664   98966 action_handler.go:141] the Cluster API is unavailable
I0922 23:02:08.212244   98966 machine_scale_executor.go:113] Building azure cloud provider.
I0922 23:02:08.212277   98966 machine_scale_executor.go:154] Creating Azure Manager with default configuration.
I0922 23:02:08.212305   98966 azure_manager.go:461] Starting azure manager with subscription ID "6a5d73a4-e446-4c75-8f18-073b2f60d851"
I0922 23:02:38.180552   98966 action_handler.go:359] Received an action SUSPEND for entity VIRTUAL_MACHINE [aks-agentpool-36973178-2]
I0922 23:02:38.234433   98966 action_handler.go:176] Now wait for action result
I0922 23:02:39.423370   98966 machine_scaler_cp.go:71] Executing action Suspend on node aks-agentpool-36973178-2 with node parent pool size 3.
I0922 23:02:39.621992   98966 azure_kubernetes_service_pool.go:282] VM name got to delete: aks-agentpool-36973178-2
I0922 23:02:39.985006   98966 azure_util.go:157] found nic name for VM (MC_adveng_aks-virtual_westus/aks-agentpool-36973178-2): aks-agentpool-36973178-nic-2
I0922 23:02:39.985043   98966 azure_util.go:160] deleting VM: MC_adveng_aks-virtual_westus/aks-agentpool-36973178-2
I0922 23:02:39.985073   98966 azure_util.go:164] waiting for VirtualMachine deletion: MC_adveng_aks-virtual_westus/aks-agentpool-36973178-2
I0922 23:07:32.457575   98966 azure_util.go:173] deleting nic: MC_adveng_aks-virtual_westus/aks-agentpool-36973178-nic-2
I0922 23:07:32.457673   98966 azure_util.go:176] waiting for nic deletion: MC_adveng_aks-virtual_westus/aks-agentpool-36973178-nic-2
I0922 23:07:34.056537   98966 azure_util.go:205] deleting managed disk: MC_adveng_aks-virtual_westus/aks-agentpool-36973178-2_OsDisk_1_0a2d4e6a2c354650b0237bdb89c4e56e
E0922 23:07:35.052708   98966 azure_kubernetes_service_pool.go:239] size-decreasing request of 2 is smaller than min size 3
E0922 23:07:35.052756   98966 azure_kubernetes_service_pool.go:314] Failed to set size for agent pool "agentpool" with error: size-decreasing request of 2 is smaller than min size 3
I0922 23:09:25.719530   98966 action_handler.go:336] action keepAlive goroutine exit.
• [SLOW TEST:446.712 seconds]
Machine Scaling via Cloud Provider
/Users/irfanurrehman/src/github.com/turbonomic/kubeturbo/test/integration/machine_scaling_cp.go:16
  executing action suspend machine
  /Users/irfanurrehman/src/github.com/turbonomic/kubeturbo/test/integration/machine_scaling_cp.go:71
    should result in the node being deleted
    /Users/irfanurrehman/src/github.com/turbonomic/kubeturbo/test/integration/machine_scaling_cp.go:72
------------------------------

Ran 2 of 6 Specs in 1144.377 seconds
SUCCESS! -- 2 Passed | 0 Failed | 0 Pending | 4 Skipped
--- PASS: TestIntegration (1144.38s)
PASS
Process 98966 has exited with status 0
Detaching
dlv dap (98931) exited with code: 0
```

**Comment by enlinxu** [comment]
@irfanurrehman 
The command "make fmtcheck" exited with 0.
235.88s$ make vet
# github.com/turbonomic/kubeturbo/test/integration
vet: test/integration/machine_scaling_cp.go:47:94: not enough arguments in call to action.NewActionHandlerConfig
Makefile:53: recipe for target 'vet' failed
make: *** [vet] Error 2
The command "make vet" exited with 2.

**Comment by enlinxu** [comment]
@irfanurrehman Please add more details to the PR to explain the Intent, Solution and Test(with Screenshot). Thanks.

**Pull request closed without merging**
