### PR TITLE
Discovery tests

### PR DESCRIPTION
**Pull request by irfanurrehman**
This submits a test which compares total number of entities and groups discovered.
There is a bunch of more items that I could identify while writing this and are captured in TODOs. I will continue adding test as per those items.

This is on top of https://github.com/turbonomic/kubeturbo/pull/484 as the discovery needs to be external to the cluster.

### CODE REVIEW

**Comment by irfanurrehman** [comment]
@enlinxu @ading1977 @marvelyue I would appreciate if you can please take a look.

**Review by enlinxu — APPROVED** [review]
Sorry for the delay @irfanurrehman , really nice and let's extend it!

**Comment by enlinxu** [comment]
@irfanurrehman  Shall we merge ?

**Comment by irfanurrehman** [comment]
Thanks for the review @enlinxu

**Pull request merged**
