### PR TITLE
[OM-79471]: Updated supply chain factory to specify merge strategy.

### PR DESCRIPTION
**Pull request by amd-ibm**
# Intent

Resolve an issue where related tags for kubernetes nodes disappear during stitching.

# Fix

Updated supply chain factory to specify the merge properties strategy, instead of using the hard-coded value on the backend.

# Test

Manually tested with changes to opsmgr, turbo-go-sdk, and XL in the lab to verify the tags are merged and displayed in the UI. Ran unit tests.

### CODE REVIEW

**Comment by enlinxu** [comment]
We need the go-sdk change in first?

**Comment by amd-ibm** [comment]
> We need the go-sdk change in first?

Yes. That PR is [here](https://github.com/turbonomic/turbo-go-sdk/pull/130)

**Comment by enlinxu** [comment]
@amd-ibm I merged the sdk change, please update the go.mod and commit to trigger the build again.

**Comment by ading1977** [comment]
@amd-ibm , you probably need to do `go mod vendor` to commit the changes too.

**Review by enlinxu — APPROVED** [review]

**Review by ading1977 — APPROVED** [review]

**Pull request merged**
