### PR TITLE
kubeturbo certified operator 8.6.0

### PR DESCRIPTION
**Pull request by esara**

### CODE REVIEW

**Review by ading1977 — APPROVED** [review]

**Comment by ading1977** [comment]
The `RELATED_IMAGE_KUBETURBO` in [here](https://github.com/turbonomic/kubeturbo/pull/703/files#diff-620b29402a5e94db00735f5c9401e580b56bcddd10adc469ca05b23d60cb16ee) seems to be wrong?

It is still referring to `8.5.5` image:

image

**Comment by esara** [comment]
yes, I am waiting on the 8.6.0 image to be built and I will updated the sha image id, please do not merge until then...

**Comment by esara** [comment]
> The `RELATED_IMAGE_KUBETURBO` in [here](https://github.com/turbonomic/kubeturbo/pull/703/files#diff-620b29402a5e94db00735f5c9401e580b56bcddd10adc469ca05b23d60cb16ee) seems to be wrong?
> 
> It is still referring to `8.5.5` image:
> 
> image

updated

**Comment by esara** [comment]
@ading1977 are you ok to merge?

**Review by enlinxu — APPROVED** [review]

**Pull request merged**
