### PR TITLE
Fix quota update race

### PR DESCRIPTION
**Pull request by irfanurrehman**
Implements https://vmturbo.atlassian.net/browse/OM-66786

This is on top of #524 and only the last 2 commits are reviewable here

### CODE REVIEW

**Comment by irfanurrehman** [comment]
Rebased!

**Comment by ading1977** [comment]
The change looks fine to me. I just have one question, do we want to synchronize the `cleanupQuotas` during restart using the same lock?

**Comment by irfanurrehman** [comment]
> The change looks fine to me. I just have one question, do we want to synchronize the `cleanupQuotas` during restart using the same lock?

The `cleanupQuotas` during restart would happen before anything else runs in kubeturbo. Also any failure (well except 1 specific failure type) during this process will restart kubeturbo. A lock is therefor not needed.

**Comment by ading1977** [comment]
> > The change looks fine to me. I just have one question, do we want to synchronize the `cleanupQuotas` during restart using the same lock?
> 
> The `cleanupQuotas` during restart would happen before anything else runs in kubeturbo. Also any failure (well except 1 specific failure type) during this process will restart kubeturbo. A lock is therefor not needed. Is there any specific scenario that comes to your mind to use a lock at this stage.. ?

Thanks, I thought `cleanupQuotas` is done in a goroutine, but after another look it is not. So it should be fine.

**Review by ading1977 — APPROVED** [review]
LGTM

**Review by marvelyue — APPROVED** [review]
LGTM

**Pull request merged**
