### PR TITLE
Add volume to vm relationship to show connection in unstitched env

### PR DESCRIPTION
**Pull request by irfanurrehman**
This partly fixes https://vmturbo.atlassian.net/browse/OM-62195.
The commodity can also be stitched to reflect the used value against those reported for the virtual machine too. It does not work though. So if unstitched the vm will report right values, but after stitching vm shows used same as capacity. I think the stitching is useful and will try to figure out some way of doing that.

### CODE REVIEW

**Comment by irfanurrehman** [comment]
Rebased!
I am waiting for review on this one.
cc @ading1977 @enlinxu @marvelyue

**Comment by enlinxu** [comment]
Discussed with @irfanurrehman , this review will help populating the VM storage amount bought when the stitching is working. Right now we still need to figure out how to make the stitching work, due to the key inconsistency. Will re-visit once we can make the stitching work.

**Comment by enlinxu** [comment]
@irfanurrehman  based on our discussion, can we close this PR?

**Comment by irfanurrehman** [comment]
ok @enlinxu closing this for now. I will get back to this again when I can find a way to stitch the `STORAGE_AMOUNT` commodity on VMs.

**Comment by enlinxu** [comment]
@irfanurrehman I thought we decided to fix this through supply chain navigation and you already had code for that, is that not the case?

**Pull request closed without merging**
